{% set name = "django-environ" %}
{% set version = "0.4.5" %}
{% set sha256 = "6c9d87660142608f63ec7d5ce5564c49b603ea8ff25da595fd6098f6dc82afde" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - six

about:
  home: https://github.com/joke2k/django-environ
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Django-environ allows you to utilize 12factor inspired environment variables to configure your Django application.'
  description: |
    Django-environ allows you to utilize 12factor inspired environment variables to configure your Django application.
    This module is a merge of:
      -envparse
      -honcho
      -dj-database-url
      -dj-search-url
      -dj-config-url
      -django-cache-url

    and inspired by:
      -12factor
      -12factor-django
      -Two Scoops of Django

  doc_url: https://django-environ.readthedocs.io/en/latest/
  dev_url: https://github.com/joke2k/django-environ

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
