travis:
  secure:
    BINSTAR_TOKEN: bKBUIcfp39IzGCZz/dG4Ife2ibH8lM5iENdQBs0HHSVtTzr6hyILeQLMPkvOEzljpg7ff2Y8ntULpEhDk5pP46hlWK35lI3APsCxF6d0B8GaOM3JrfJzTZksjmqvVi5Imaqhu0LMcIktTHAsdEoo6zcbhzKYViOuOKLktJ0kYfXMWlQWNNFzLG5IV3FdMpHg9d99LUi0YWZrs/I4/5KeUI9sRbdmOsUsQQduVTIOWDDsC4l8rL7a+Aqeh+04l59bdlqVeeusrnE7FGa/JdKMb//H3upxa3lsP3Wh/T/fDRiYjb7ptO8nfwC1roHubUFq5GjsajWaY7F8UCYhAQdNnnZrPVPc55RFVyui0FKo4zPJoItc41yG/cAGRdEdCj2AX65cIfDE6GzMsab3lcbGaNBpLk/mePo2ZrpfH+STHigcLh/7QPDIPr/mNmM5J976qU5V9WYkVpMxg3Q9kv+nXv633EIc5qgBNtLwqdVJH5s5rBn1MggMxvdk0v0lEmn9p2jtUHsnO571FnXUZKIo/M6AHFW5UatDS8PXQJ8jNu1245U2xgHipAs5cNyGg5t3DVvqF//5zafK8sFpoiqFYfF6lEYEaA6noaYz7cxSHRQm9nfRxeFTT0W52pX4YDPO35m2FxDSdYGYT69A/JGo4Kxit0DgIU4R8MRzhJGr//w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
