travis:
  secure:
    BINSTAR_TOKEN: JVf+9C/KKJB7x3v9SqctkFukKtFApk5y2UuVZCI9s8d0Kxk5uSSbBG60+7P9PwHZ1VN9NxaAFkbi9wpBo4lE38io9KxPVgAg/f8Ke3KmUT93Ctu6WCh9TEQZeE0VXf6wTf98/b5n8NGwzaQCiUTUIBJgvLF0qKcoKEgST6S53o+o9spG8kIYT4o3LNM72oJkx/PS8K3JWWOi0uyn4YDJNR7mcDIzDCTJQtCC4UiUwaxqxpvGJqjiEO8e1OmEKLj8qc+BDYbREyS54RZzmyGbiEKWWI1nehTWYmfXCRwUDuF+Jd5Bhz1x3bmoQCrsWOHkBD3hPemagte8wFrDFuYNdoh7mrMIw1Qe2xXuNa+OV4gvHyPPc2aSANw5hqSR8PkmLPxX0oigRDtslN8rKaiCQqro1kGZWmAGf9xNSPfwTdo1EEfSsslq6P4il6foWzJB7mT4BA9BFEb8fg1iau0awd4oj/qIcjEPy60Rz9sZd5WG+TMyHttFbL0X8tMFu0bryKYH1YprWut/MbDVm3g5pt2O+L6a5U60ZFX/eWgdDB32mD71/UIeTJ0FgiJCp6b/Bj3OojNqfgCFuCk+WotlVfTMRMm2icD2JcNh+PSj4WEEJlQKCYIJkSKdQAdLEyQ/p8wtXOBRo1BzoF4/2As2Xfn1U+Pa8ClcBilrNIPd5e0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
